version: '3.5'
services:
  authority:
    image: 5minds/processcube_authority:2024-1
    ports:
      - 11560:11560
    volumes:
      - ./.processcube/authority/config/config.json:/etc/authority/config/config.json
      - ./.processcube/authority/config/upeSeedingData.json:/etc/authority/upeSeedingData.json
    environment:
      - CONFIG_PATH=/etc/authority/config/config.json
      - UPE_SEED_PATH=/etc/authority/upeSeedingData.json

  engine:
    image: 5minds/engine:17.0.1-extensions-0.27.0
    ports:
      - 8000:8000
    volumes:
      - ./.processcube/engine/db:/database
      - ./processes:/processes:ro
    environment:
      - httpServer__port=8000
      - application__name=processcube-nodered-howto.de
      - database__storage=/database/engine.sqlite
    command: --seed-dir=/processes

  nodered:
    image: 5minds/processcube_nodered:howto
    build:
      context: nodered
    ports:
      - 1880:1880
    environment:
      - ENGINE_URL=http://engine:8000
      - FLOWS=/nodered/example-flows.json
    volumes:
      - ./nodered/:/nodered/